export const DEFAULT_ACTIVITIES_MAP = {
    'yamac-parasutu-deneyimi': {
        _id: '507f1f77bcf86cd799439011',
        slug: 'yamac-parasutu-deneyimi',
        name: 'Yamaç Paraşütü Deneyimi',
        category: 'paragliding',
        description: 'Profesyonel pilotlarımız eşliğinde gökyüzünde unutulmaz bir deneyim yaşayın. Fethiye Ölüdeniz\'in muhteşem manzarasını kuşbakışı görün.',
        price: 3500,
        discountPrice: 2800,
        duration: '25-30 dakika',
        location: 'Fethiye, Ölüdeniz',
        maxGuests: 1,
        includes: ['Profesyonel pilot eşliğinde uçuş', 'Sigorta', 'Ücretsiz video ve fotoğraf çekimi', 'Transfer hizmeti'],
        excludes: ['Kişisel harcamalar'],
        image: '/images/paragliding.png',
    },
    'gyrocopter-turu': {
        _id: '507f1f77bcf86cd799439012',
        slug: 'gyrocopter-turu',
        name: 'Gyrocopter Turu',
        category: 'gyrocopter',
        description: 'Gyrocopter ile gökyüzünde özgürce süzülün. Deneyimli pilotlarımız ile güvenli ve heyecan verici bir uçuş deneyimi.',
        price: 4500,
        duration: '20-30 dakika',
        location: 'Denizli, Pamukkale',
        maxGuests: 1,
        includes: ['Profesyonel pilot', 'Tüm ekipman', 'Sigorta'],
        excludes: ['Ulaşım', 'Video kaydı'],
        image: '/images/gyrocopter.png',
    },
    'pamukkale-balon-turu': {
        _id: '507f1f77bcf86cd799439013',
        slug: 'pamukkale-balon-turu',
        name: 'Pamukkale Balon Turu',
        category: 'balloon',
        description: 'Pamukkale\'nin eşsiz beyaz travertenlerini gün doğumunda sıcak hava balonu ile keşfedin.',
        price: 8000,
        discountPrice: 6500,
        duration: '1 saat uçuş',
        location: 'Denizli, Pamukkale',
        maxGuests: 20,
        includes: ['Otel transferi', 'Kahvaltı', 'Şampanya', 'Uçuş sertifikası', 'Sigorta'],
        excludes: ['Video/Fotoğraf paketi'],
        image: '/images/balloon.png',
    },
};

export const DEFAULT_ACTIVITIES_ARRAY = Object.values(DEFAULT_ACTIVITIES_MAP);
